{% set name = "jupyterhub-ldapauthenticator" %}
{% set version = "2.0.0" %}
{% set sha256 = "b4b9d107e2300970409e5598f05d5b9fe9b666327da98895a33b855578925359" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - jupyterhub >=4.1.6
    - ldap3 >=2.9.1
    - traitlets

test:
  imports:
    - ldapauthenticator

about:
  home: https://github.com/jupyterhub/ldapauthenticator
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: LDAP Authenticator for JupyterHub

extra:
  recipe-maintainers:
    - dhirschfeld
    - minrk
    - consideRatio
